name: voxf
version: 0.0.1
synopsis: game
description: game
maintainer: ivxvm <ivxvm@protonmail.com>
github: ivxvm/voxf
category: Gamedev

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base >= 4.16
    - linear >= 1.21
    - containers >= 0.6
  default-extensions:
    - OverloadedRecordDot
    - DuplicateRecordFields
    - DeriveGeneric
    - DeriveAnyClass
    - StandaloneDeriving
