name: voxf
version: 0.0.1
synopsis: game
description: game
maintainer: ivxvm <ivxvm@protonmail.com>
github: ivxvm/voxf
category: Gamedev

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base >= 4.16
    - containers >= 0.6
    - vector >= 0.12
    - linear >= 1.21
    - mtl >= 2.2
    - gl >= 0.9
    - GLFW-b >= 3.3
    - atlas >= 0
    - JuicyPixels >= 3.3
  default-extensions:
    - Strict
    - OverloadedRecordDot
    - DuplicateRecordFields
    - FlexibleContexts
    - DeriveGeneric
    - DeriveAnyClass
    - StandaloneDeriving
    - PatternSynonyms
    - PartialTypeSignatures
    - TypeApplications
  ghc-options:
    - -Werror=incomplete-patterns
